scrape_configs:
  - job_name: 'DemoApp1Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['demoapp1:8090']
        labels:
          application: 'demoapp2'
  - job_name: 'DemoApp2Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['demoapp2:8092']
        labels:
          application: 'demoapp1'

