server:
  http_listen_port: 3100

positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [ __meta_docker_container_name ]
        regex: "/(.+)"
        target_label: container
      - source_labels: [ __meta_docker_container_name ]
        action: replace
        target_label: job
        regex: "(.+)"
